import uuid

from sqlalchemy import text

from integ.base_integration_test import BaseIntegrationTestSuite
from integ.helpers.api_helpers import process_streaming_result
from integ.helpers.auth import cleanup_framework_test_admin, cleanup_test_user, create_active_user_with_id
from integ.response_utils import extract_data

PROVIDER_DATA = {
    "name": "Test Local Provider",
    "provider_type": "local",
    "api_endpoint": "endpoint",
    "is_active": True,
}

MODEL_DATA = {
    "model_name": "local-echo",
    "display_name": "Local Echo Test Model",
    "description": "Local echo model for integration testing",
    "context_window": 8192,
    "max_tokens": 4096,
    "supports_streaming": True,
    "supports_functions": False,
    "supports_vision": False,
}

MODEL_CONFIG_DATA = {
    "name": "Test Chat Assistant",
    "description": "Test model configuration for chat integration",
    "is_active": True,
    "created_by": "test-user",
    "knowledge_base_ids": [],
}


class ChatRegenerateIntegrationTest(BaseIntegrationTestSuite):
    """Integration tests for chat message regeneration and variant lineage."""

    def get_suite_name(self) -> str:
        return "Chat Regenerate Integration"

    def get_suite_description(self) -> str:
        return "Validates regenerate endpoint (streaming and non-streaming) and message variant lineage."

    def get_test_functions(self):
        return [
            self.test_regenerate_creates_variant_and_links_lineage,
            self.test_regenerate_backfills_legacy_target_lineage,
            self.test_zz_teardown_test_admin,
        ]

    async def test_zz_teardown_test_admin(self, client, db, auth_headers):
        """Sentinel teardown — must run last. Deletes the framework-created
        test-admin user so the suite leaves the DB clean. Mirrors the raw
        SQL the framework uses in `_create_admin_user` (admin can't delete
        itself via API).
        """
        await cleanup_framework_test_admin(db)

    async def _create_user_and_auth(self, client, admin_headers) -> tuple[dict, str]:
        """Returns (headers, user_id) so the caller can clean up the user in a
        try/finally — the framework's auto-cleanup doesn't reliably match the
        emails generated by `create_active_user_headers`, so explicit teardown
        prevents Stripe-seat orphans across test runs.
        """
        return await create_active_user_with_id(client, admin_headers)

    async def _create_conversation(self, client, admin_headers, user_headers):
        # Unique suffix to avoid name collisions
        suffix = uuid.uuid4().hex[:8]
        provider_payload = {**PROVIDER_DATA, "name": f"{PROVIDER_DATA['name']} {suffix}"}

        # Create provider with admin auth
        provider_response = await client.post("/api/v1/llm/providers", json=provider_payload, headers=admin_headers)
        print("DEBUG provider_response:", provider_response.status_code, provider_response.text)
        assert provider_response.status_code == 201, provider_response.text
        provider_id = extract_data(provider_response)["id"]

        # Create model under provider
        model_response = await client.post(
            f"/api/v1/llm/providers/{provider_id}/models", json=MODEL_DATA, headers=admin_headers
        )
        print("DEBUG model_response:", model_response.status_code, model_response.text)
        assert model_response.status_code == 200, model_response.text

        # Create model configuration with admin auth
        model_config_data = {
            **MODEL_CONFIG_DATA,
            "llm_provider_id": provider_id,
            "model_name": MODEL_DATA["model_name"],
        }
        config_response = await client.post(
            "/api/v1/model-configurations", json=model_config_data, headers=admin_headers
        )
        print("DEBUG config_response:", config_response.status_code, config_response.text)
        assert config_response.status_code == 201, config_response.text
        model_config_id = extract_data(config_response)["id"]

        # Create conversation with model config as the regular user
        resp = await client.post(
            "/api/v1/chat/conversations",
            json={"title": "Regen Test", "model_configuration_id": model_config_id},
            headers=user_headers,
        )
        print("DEBUG create_conversation:", resp.status_code, resp.text)
        assert resp.status_code == 200, resp.text
        conv = extract_data(resp)
        return conv["id"]

    async def _send_user_message(self, client, conv_id, headers, text="Hello world"):
        resp = await client.post(
            f"/api/v1/chat/conversations/{conv_id}/send",
            json={"message": text},
            headers=headers,
        )
        assert resp.status_code == 200
        msg = await process_streaming_result(resp)
        # Server returns the assistant message created in response
        assert msg["role"] == "assistant"
        return msg

    async def _list_messages(self, client, conv_id, headers):
        resp = await client.get(f"/api/v1/chat/conversations/{conv_id}/messages", headers=headers)
        assert resp.status_code == 200, resp.text
        return extract_data(resp)

    async def test_regenerate_creates_variant_and_links_lineage(self, client, db, auth_headers):
        # Use admin headers from test runner to create provider/model-config
        admin_headers = auth_headers
        user_headers, user_id = await self._create_user_and_auth(client, admin_headers)
        try:
            conv_id = await self._create_conversation(client, admin_headers, user_headers)

            assistant_msg = await self._send_user_message(client, conv_id, user_headers, text="Say hi")

            # Regenerate the assistant message (non-stream)
            regen = await client.post(
                f"/api/v1/chat/messages/{assistant_msg['id']}/regenerate",
                json={},
                headers=user_headers,
            )
            assert regen.status_code == 200, regen.text
            regen_msg = await process_streaming_result(regen)

            # Validate lineage
            root = assistant_msg.get("parent_message_id") or assistant_msg["id"]
            assert regen_msg["parent_message_id"] == root
            assert isinstance(regen_msg.get("variant_index"), int)
            assert regen_msg["variant_index"] >= 1
            assert regen_msg["role"] == "assistant"
            assert regen_msg["conversation_id"] == conv_id

            # Messages should include both assistant variants
            messages = await self._list_messages(client, conv_id, user_headers)
            assistant_variants = [m for m in messages if m["role"] == "assistant"]
            assert len(assistant_variants) >= 2
        finally:
            await cleanup_test_user(client, admin_headers, user_id)

    async def test_regenerate_backfills_legacy_target_lineage(self, client, db, auth_headers):
        """SHU-759 / AC #N6: regenerating a legacy assistant message — one
        whose `parent_message_id` and `variant_index` are NULL — backfills
        the target's lineage in the same fresh-session transaction as the
        new assistant variant write.

        The fold-in of the regen lineage logic into `_finalize_variant_phase`
        (step 7) preserved the legacy backfill semantics from the removed
        `regen_stream` wrapper. This test guards against accidentally
        dropping that backfill on future refactors: legacy conversations
        whose assistant messages predate the lineage columns would
        otherwise lose variant grouping on regenerate.
        """
        admin_headers = auth_headers
        user_headers, user_id = await self._create_user_and_auth(client, admin_headers)
        try:
            conv_id = await self._create_conversation(client, admin_headers, user_headers)

            assistant_msg = await self._send_user_message(client, conv_id, user_headers, text="Say hi")
            target_id = assistant_msg["id"]

            # Force the assistant message into legacy shape: no parent / no variant_index.
            # The fresh-session lineage backfill in _finalize_variant_phase is what we
            # want this regenerate to exercise.
            await db.execute(
                text(
                    "UPDATE messages SET parent_message_id = NULL, variant_index = NULL "
                    "WHERE id = :id"
                ),
                {"id": target_id},
            )
            await db.commit()

            # Confirm the legacy state landed.
            row = (
                await db.execute(
                    text(
                        "SELECT parent_message_id, variant_index FROM messages WHERE id = :id"
                    ),
                    {"id": target_id},
                )
            ).first()
            assert row is not None
            assert row[0] is None, f"setup precondition failed: parent_message_id is {row[0]!r}, expected NULL"
            assert row[1] is None, f"setup precondition failed: variant_index is {row[1]!r}, expected NULL"

            # Regenerate the legacy assistant message. Finalize should backfill
            # target.parent_message_id = target_id (self-root) and variant_index = 0,
            # and write the new variant at variant_index = 1.
            regen = await client.post(
                f"/api/v1/chat/messages/{target_id}/regenerate",
                json={},
                headers=user_headers,
            )
            assert regen.status_code == 200, regen.text
            regen_msg = await process_streaming_result(regen)

            # New variant lineage
            assert regen_msg["parent_message_id"] == target_id, (
                f"new variant should point at target as root; got {regen_msg.get('parent_message_id')!r}"
            )
            assert regen_msg.get("variant_index") == 1, (
                f"new variant should be variant_index=1 (after the backfilled root at 0); "
                f"got {regen_msg.get('variant_index')!r}"
            )

            # Target lineage backfilled in the SAME transaction the new variant was written in.
            # Re-fetch directly from DB to be sure we see committed state.
            row = (
                await db.execute(
                    text(
                        "SELECT parent_message_id, variant_index FROM messages WHERE id = :id"
                    ),
                    {"id": target_id},
                )
            ).first()
            assert row is not None
            assert row[0] == target_id, (
                f"target.parent_message_id should be backfilled to its own id (self-root); got {row[0]!r}"
            )
            assert row[1] == 0, (
                f"target.variant_index should be backfilled to 0 (root of its variant group); got {row[1]!r}"
            )
        finally:
            await cleanup_test_user(client, admin_headers, user_id)


if __name__ == "__main__":
    ChatRegenerateIntegrationTest().run()
