"""Pydantic schemas for query synthesis (SHU-353).

These schemas define the structure of synthesized queries generated by
QuerySynthesisService and stored in the DocumentQuery table.
"""

from pydantic import BaseModel, Field


class SynthesizedQuery(BaseModel):
    """A single synthesized query that a document can answer.

    Queries encompass questions, imperatives, and declarative searches.
    """

    query_text: str = Field(
        ...,
        description="The synthesized query text",
    )
    query_type: str = Field(
        default="interrogative",
        description="Type: interrogative, imperative, declarative, interpretive, relational, temporal, structural",
    )
    topic_covered: str = Field(
        default="",
        description="Which main idea/topic this query addresses",
    )


class MainIdea(BaseModel):
    """A main idea or topic identified in a document."""

    topic: str = Field(..., description="The main idea or topic")
    description: str = Field(default="", description="Brief description of what this topic covers")


class QuerySynthesisResult(BaseModel):
    """Result of synthesizing queries for a document."""

    queries: list[SynthesizedQuery] = Field(
        default_factory=list,
        description="List of synthesized queries",
    )
    main_ideas: list[MainIdea] = Field(
        default_factory=list,
        description="Main ideas identified in the document",
    )
    success: bool = Field(True, description="Whether synthesis succeeded")
    error: str | None = Field(None, description="Error message if failed")
    tokens_used: int = Field(0, description="Total tokens used for synthesis")
    duration_ms: int = Field(0, description="Total synthesis duration in milliseconds")
